### ISSUE TITLE
A user account is required to confirm the properties of the current Data Collector Set.

### ISSUE THREAD

**Issue by lgp1985** [microsoft/busiotools#56]
Hey,
I'm unable to run usbtrace.cmd

the command
```
logman update trace -n usbtrace -p Microsoft-Windows-USB-USBXHCI (Default,PartialDataBusTrace,StateMachine)
```
fails with error
```
A user account is required to confirm the properties of the current Data Collector Set.
Uma conta de usuário é necessária para confirmar as propriedades do Conjunto de Coletores de Dados atual.
```
no matter if I run it as administrator or not, but I see that if I run it on a different machine it works.

Works at: Windows Version 1809 (OS Build 17763.737) (en-US)
Fails at: Windows Versão 1903 (Compilação do Sistema Operacional 18990.1) (pt-BR)

**Comment by davidpreetham** [comment]
@lgp1985 is it working you? I am also facing same issue.. version 1903 its not working..
do you have any idea how can I collect USB traces ?

**Comment by loosetile2** [comment]
Please note this issue may be resolved in the recently released KB4550945

Contained with the list of changes is "Addresses an issue that causes an error in logman.exe. The error is, "A user account is required in order to commit the current Data collector Set properties." "

Let me know how it goes

Cheers
